from __future__ import annotations

from .types import EmailEnvConfig, EmailMessage, InboxEmail, Scenario, UserProfile


def default_scenarios() -> list[Scenario]:
    founder_profile = UserProfile(
        role="founder",
        prefers_clarify_before_escalation=True,
        vip_senders=["investor@northstar.vc", "chief@clientco.ai"],
        same_day_threshold_hours=18,
    )

    return [
        Scenario(
            scenario_id="launch_week",
            description="Inbox during a product launch with hidden blockers and competing priorities.",
            user_profile=founder_profile,
            thread_history={
                "thread-1": "The client deliverable is due tomorrow morning and design assets are still pending.",
                "thread-2": "Investor update is due this evening but can be delegated if draft exists.",
                "thread-3": "Recruiting outreach is useful but not business critical this week.",
            },
            pending_tasks=[
                "Ship launch assets before tomorrow 09:00",
                "Send investor update by tonight 20:00",
            ],
            emails=[
                EmailMessage(
                    email_id="email-1",
                    sender="designer@studio.dev",
                    sender_role="vendor",
                    subject="Quick question on the homepage asset export",
                    body="Need your confirmation on which hero version to export. If I do not hear back in 3 hours, the client deck will slip.",
                    thread_id="thread-1",
                    explicit_urgency="low",
                    hidden_priority="high",
                    hidden_action="reply",
                    hidden_deadline_hours=3,
                    blocks_deliverable=True,
                    vip_sender=False,
                ),
                EmailMessage(
                    email_id="email-2",
                    sender="investor@northstar.vc",
                    sender_role="investor",
                    subject="Can you share this month's retention view?",
                    body="No rush if tomorrow works, but I would love a quick snapshot before my partner meeting.",
                    thread_id="thread-2",
                    explicit_urgency="medium",
                    hidden_priority="medium",
                    hidden_action="draft",
                    hidden_deadline_hours=10,
                    blocks_deliverable=False,
                    vip_sender=True,
                ),
                EmailMessage(
                    email_id="email-3",
                    sender="recruiter@talentflow.io",
                    sender_role="recruiter",
                    subject="Following up on engineering candidates",
                    body="Wanted to bubble this up in case you had bandwidth today.",
                    thread_id="thread-3",
                    explicit_urgency="medium",
                    hidden_priority="low",
                    hidden_action="defer",
                    hidden_deadline_hours=None,
                    blocks_deliverable=False,
                    vip_sender=False,
                ),
                EmailMessage(
                    email_id="email-4",
                    sender="chief@clientco.ai",
                    sender_role="client",
                    subject="Need confirmation before tomorrow's steering call",
                    body="Please confirm whether your team can commit to the revised milestone list before 17:00.",
                    thread_id="thread-1",
                    explicit_urgency="high",
                    hidden_priority="high",
                    hidden_action="escalate",
                    hidden_deadline_hours=6,
                    blocks_deliverable=True,
                    vip_sender=True,
                ),
            ],
            expected_outcomes={
                "email-1": {"priority": "high", "action_type": "reply", "deadline_hours": 3},
                "email-2": {"priority": "medium", "action_type": "draft", "deadline_hours": 10},
                "email-3": {"priority": "low", "action_type": "defer", "deadline_hours": None},
                "email-4": {"priority": "high", "action_type": "escalate", "deadline_hours": 6},
            },
            drift_notes=[
                "Implicit urgency hidden in a vendor message",
                "Investor email sounds soft but still carries a same-day expectation",
            ],
        ),
        Scenario(
            scenario_id="policy_drift",
            description="Inbox after an escalation-policy change and a new VIP contact being introduced.",
            user_profile=UserProfile(
                role="executive_assistant",
                prefers_clarify_before_escalation=False,
                vip_senders=["ceo@acme.ai", "legal@partner.org"],
                same_day_threshold_hours=12,
            ),
            thread_history={
                "thread-10": "The CEO wants customer escalations routed immediately if revenue renewal is at risk.",
                "thread-11": "Travel changes can be deferred unless they impact tomorrow morning meetings.",
                "thread-12": "Legal review is newly marked as VIP due to contract signature week.",
            },
            pending_tasks=[
                "Protect renewal call scheduled tomorrow 08:30",
                "Finalize partner contract today",
            ],
            emails=[
                EmailMessage(
                    email_id="email-10",
                    sender="csm@renewals.app",
                    sender_role="customer_success",
                    subject="Customer may pause renewal without pricing clarification",
                    body="Sharing a heads-up before tomorrow's renewal call. They need pricing confirmation tonight to stay on track.",
                    thread_id="thread-10",
                    explicit_urgency="medium",
                    hidden_priority="high",
                    hidden_action="escalate",
                    hidden_deadline_hours=8,
                    blocks_deliverable=True,
                    vip_sender=False,
                ),
                EmailMessage(
                    email_id="email-11",
                    sender="travel@airline.com",
                    sender_role="travel",
                    subject="Seat update for next month's conference",
                    body="No action needed right now. Reply only if you want to change the selection later.",
                    thread_id="thread-11",
                    explicit_urgency="low",
                    hidden_priority="low",
                    hidden_action="defer",
                    hidden_deadline_hours=None,
                    blocks_deliverable=False,
                    vip_sender=False,
                ),
                EmailMessage(
                    email_id="email-12",
                    sender="legal@partner.org",
                    sender_role="legal",
                    subject="Final contract redlines attached",
                    body="Please confirm acceptance before 16:00 so we can execute the agreement today.",
                    thread_id="thread-12",
                    explicit_urgency="high",
                    hidden_priority="high",
                    hidden_action="reply",
                    hidden_deadline_hours=5,
                    blocks_deliverable=True,
                    vip_sender=True,
                ),
            ],
            expected_outcomes={
                "email-10": {"priority": "high", "action_type": "escalate", "deadline_hours": 8},
                "email-11": {"priority": "low", "action_type": "defer", "deadline_hours": None},
                "email-12": {"priority": "high", "action_type": "reply", "deadline_hours": 5},
            },
            drift_notes=[
                "Escalation policy changed for renewal risk",
                "Legal became a new VIP contact during contract week",
            ],
        ),
    ]


def dynamic_environment_configs() -> list[EmailEnvConfig]:
    founder_profile = UserProfile(
        role="founder",
        prefers_clarify_before_escalation=True,
        vip_senders=["boss@company.ai", "client@northstar.com"],
        same_day_threshold_hours=12,
    )

    ops_profile = UserProfile(
        role="executive_assistant",
        prefers_clarify_before_escalation=False,
        vip_senders=["ceo@company.ai", "legal@partner.org"],
        same_day_threshold_hours=10,
    )

    return [
        EmailEnvConfig(
            config_id="founder_launch_dynamic",
            description="Launch-week inbox where unresolved work triggers follow-ups and new email arrivals.",
            user_profile=founder_profile,
            max_steps=7,
            initial_emails=[
                InboxEmail(
                    email_id="dyn-1",
                    sender="client@northstar.com",
                    sender_importance="client",
                    subject="Need approval before 4 PM milestone review",
                    body="Please confirm whether your team can commit to the revised milestone list before 4 PM.",
                    priority="high",
                    urgency=True,
                    visible_urgency=True,
                    deadline_step=2,
                    hidden_intent="client_confirmation",
                    expected_action="escalate_email",
                    expected_tone="professional",
                    thread_id="dyn-thread-1",
                    tags=["deadline", "milestone"],
                ),
                InboxEmail(
                    email_id="dyn-2",
                    sender="design@studio.dev",
                    sender_importance="client",
                    subject="Quick export question",
                    body="Which hero image should we export for tomorrow's client deck?",
                    priority="high",
                    urgency=True,
                    visible_urgency=False,
                    deadline_step=1,
                    hidden_intent="asset_blocker",
                    expected_action="generate_reply",
                    expected_tone="helpful",
                    thread_id="dyn-thread-2",
                    tags=["blocker", "design"],
                ),
                InboxEmail(
                    email_id="dyn-3",
                    sender="friend@alumni.org",
                    sender_importance="friend",
                    subject="Dinner this weekend?",
                    body="No pressure, just checking whether Saturday works for dinner.",
                    priority="low",
                    urgency=False,
                    visible_urgency=False,
                    deadline_step=None,
                    hidden_intent="social_message",
                    expected_action="delay_email",
                    expected_tone="friendly",
                    thread_id="dyn-thread-3",
                    tags=["personal"],
                ),
            ],
            arrivals=[
                InboxEmail(
                    email_id="dyn-4",
                    sender="boss@company.ai",
                    sender_importance="boss",
                    subject="Can you send the investor summary tonight?",
                    body="Need a crisp summary before my board prep. Late evening is still useful.",
                    priority="medium",
                    urgency=True,
                    visible_urgency=False,
                    deadline_step=4,
                    hidden_intent="board_update",
                    expected_action="generate_reply",
                    expected_tone="professional",
                    thread_id="dyn-thread-4",
                    tags=["vip", "summary"],
                ),
                InboxEmail(
                    email_id="dyn-5",
                    sender="unknown@opsmail.dev",
                    sender_importance="client",
                    subject="Need a quick yes on the API switch",
                    body="A fast yes would help. This may affect tomorrow's deployment, but details are still fuzzy.",
                    priority="medium",
                    urgency=True,
                    visible_urgency=False,
                    deadline_step=5,
                    hidden_intent="ambiguous_api_change",
                    expected_action="classify_email",
                    expected_tone="professional",
                    thread_id="dyn-thread-5",
                    tags=["ambiguous", "ops"],
                ),
            ],
            stochastic_arrival_rate=0.45,
            time_budget_per_step=1,
            random_seed=11,
        ),
        EmailEnvConfig(
            config_id="ops_fire_drill_dynamic",
            description="Ops inbox with revenue-risk escalation and low-value noise competing for attention.",
            user_profile=ops_profile,
            max_steps=8,
            initial_emails=[
                InboxEmail(
                    email_id="dyn-10",
                    sender="csm@renewals.app",
                    sender_importance="client",
                    subject="Renewal likely at risk without pricing clarification",
                    body="Customer needs pricing confirmation before tomorrow's renewal call or they may pause.",
                    priority="high",
                    urgency=True,
                    visible_urgency=False,
                    deadline_step=2,
                    hidden_intent="revenue_risk",
                    expected_action="escalate_email",
                    expected_tone="professional",
                    thread_id="dyn-thread-10",
                    tags=["renewal", "revenue"],
                ),
                InboxEmail(
                    email_id="dyn-11",
                    sender="travel@airline.com",
                    sender_importance="friend",
                    subject="Seat update for next month",
                    body="No action needed now. You can review this later.",
                    priority="low",
                    urgency=False,
                    visible_urgency=False,
                    deadline_step=None,
                    hidden_intent="non_urgent_travel",
                    expected_action="ignore_email",
                    expected_tone="neutral",
                    thread_id="dyn-thread-11",
                    requires_response=False,
                    tags=["travel"],
                ),
            ],
            arrivals=[
                InboxEmail(
                    email_id="dyn-12",
                    sender="legal@partner.org",
                    sender_importance="client",
                    subject="Final contract signature window closes today",
                    body="Please confirm acceptance before 5 PM so we can execute the agreement.",
                    priority="high",
                    urgency=True,
                    visible_urgency=True,
                    deadline_step=3,
                    hidden_intent="contract_signature",
                    expected_action="generate_reply",
                    expected_tone="professional",
                    thread_id="dyn-thread-12",
                    tags=["legal", "contract"],
                ),
                InboxEmail(
                    email_id="dyn-13",
                    sender="ceo@company.ai",
                    sender_importance="boss",
                    subject="Tiny favor before you log off",
                    body="Can you glance at the partner deck? It sounds small but it affects tomorrow morning's board narrative.",
                    priority="high",
                    urgency=True,
                    visible_urgency=False,
                    deadline_step=4,
                    hidden_intent="hidden_board_blocker",
                    expected_action="generate_reply",
                    expected_tone="professional",
                    thread_id="dyn-thread-13",
                    tags=["boss", "ambiguous", "board"],
                ),
            ],
            stochastic_arrival_rate=0.5,
            time_budget_per_step=1,
            random_seed=19,
        ),
    ]
